spring:
  config:
    activate:
      on-profile: "qa"
build:
  info: V1
account:
  message: "welcome to eazy bank accounts in QA"
  contactDetils:
    name: "john deo - QA"
    email: "ezybytes@mail.com"
  onCallSupport:
      - 23453344838
      - 45423836473
