spring:
  config:
    activate:
      on-profile: "prod"
build:
  info: V1
account:
  message: "welcome to eazy bank accounts - Production"
  contactDetils:
    name: "john deo - Prod - Team"
    email: "ezybytes@mail.com"
  onCallSupport:
      - 2345457838
      - 45421836473
