spring:
  config:
    activate:
      on-profile: "qa"
build:
  info: V1
account:
  message: "welcome to eazy bank accounts in QA Environments"
  contactDetils:
    name: "john deo - QA"
    email: "ezybytes@mail.com"
  onCallSupport:
      - 2340031111
      - 4500382222
