spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: V1
account:
  message: "welcome to eazy bank loans in prod Environment"
  contactDetils:
    name: "john deo - PRODUCTION - Team"
    email: "ezybytes@mail.com"
  onCallSupport:
      - 2345300111
      - 4542300222
